name: phoneotp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_storage: ^10.2.17
  liquid_swipe: ^2.1.0
  animate_do: ^2.1.0
  country_code_picker: ^2.0.2
  pinput: ^1.2.0
  flutter_native_splash: ^2.1.6
  animated_text_kit: ^4.2.1
  flutter_signin_button: ^2.0.0
  flutter_beep: ^1.0.0
  legacy_progress_dialog: ^0.1.2
  location: ^4.4.0
  csc_picker: ^0.2.6
  geocoder_flutter: ^0.2.3-prerelease
  flutter_neumorphic: ^3.2.0
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  galleryimage: ^1.2.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/phnotpimg.png
  - assets/kingdom-sign-in.gif
  - assets/welcome.jpg


  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700

    # - family: Anton
    #   fonts:
    #     - asset: assets/fonts/Anton-Regular.ttf
       
